// Generated by ts-cloud for the management dashboard â do not edit.
//
// This is the project's resolved cloud config, inlined so it needs no
// imports on the box. Credentials are deliberately absent.
export default {
  "project": {
    "name": "chrisbreuer",
    "slug": "chrisbreuer",
    "region": "us-east-1"
  },
  "cloud": {
    "provider": "hetzner",
    "attachTo": "stacks"
  },
  "mode": "server",
  "infrastructure": {
    "compute": {
      "mode": "server",
      "size": "small",
      "runtime": "bun",
      "webServer": "rpx",
      "proxy": {
        "engine": "rpx",
        "onDemandTls": true,
        "onDemandTlsEmail": "hello@stacksjs.com",
        "onDemandTlsStaging": false
      }
    }
  },
  "environments": {
    "production": {
      "type": "production",
      "deployBranch": "main",
      "region": "us-east-1",
      "variables": {
        "NODE_ENV": "",
        "LOG_LEVEL": ""
      }
    }
  },
  "sites": {
    "chrisbreuerMain": {
      "root": ".",
      "path": "/",
      "domain": "chrisbreuer.me",
      "start": "bun --conditions development storage/framework/core/buddy/src/cli.ts serve",
      "port": 3040,
      "preStart": [
        "bun install",
        "mkdir -p /var/lib/chrisbreuer",
        "bun --conditions development storage/framework/core/buddy/src/cli.ts migrate || true"
      ],
      "env": {
        "HOST": "",
        "APP_ENV": "",
        "APP_NAME": "",
        "APP_URL": "",
        "APP_KEY": "",
        "PORT_API": "",
        "DB_CONNECTION": "",
        "DB_DATABASE_PATH": ""
      }
    },
    "chrisbreuerApi": {
      "root": ".",
      "start": "bun --conditions development storage/framework/core/actions/src/serve/api.ts",
      "port": 3048,
      "preStart": [
        "bun install"
      ],
      "env": {
        "HOST": "",
        "APP_ENV": "",
        "APP_NAME": "",
        "APP_URL": "",
        "APP_KEY": "",
        "DB_CONNECTION": "",
        "DB_DATABASE_PATH": ""
      }
    },
    "chrisbreuerWww": {
      "domain": "www.chrisbreuer.me",
      "redirect": "https://chrisbreuer.me"
    }
  }
}
