// Auto-generated by stx — do not edit
// Source: resources/views/

export const routes = [
  { pattern: '/', filePath: 'resources/views/index.stx', isDynamic: false, params: [] },
  { pattern: '/about', filePath: 'resources/views/about.stx', isDynamic: false, params: [] },
  { pattern: '/apps', filePath: 'resources/views/apps.stx', isDynamic: false, params: [] },
  { pattern: '/blog', filePath: 'resources/views/blog.stx', isDynamic: false, params: [] },
  { pattern: '/goals', filePath: 'resources/views/goals.stx', isDynamic: false, params: [] },
  { pattern: '/projects', filePath: 'resources/views/projects.stx', isDynamic: false, params: [] },
  { pattern: '/uses', filePath: 'resources/views/uses.stx', isDynamic: false, params: [] },
  { pattern: '/blog/:slug', filePath: 'resources/views/blog/[slug].stx', isDynamic: true, params: ["slug"] },
] as const

export type RouteName = typeof routes[number]['pattern']
