// Auto-generated by stx — do not edit
// Source: resources/views/

export const routes = [
  { pattern: '/checkout/contact', filePath: 'storage/framework/defaults/resources/views/checkout/contact.stx', isDynamic: false, params: [] },
  { pattern: '/checkout/payment', filePath: 'storage/framework/defaults/resources/views/checkout/payment.stx', isDynamic: false, params: [] },
  { pattern: '/checkout/shipping', filePath: 'storage/framework/defaults/resources/views/checkout/shipping.stx', isDynamic: false, params: [] },
  { pattern: '/dashboard/custom-page', filePath: 'storage/framework/defaults/resources/views/dashboard/custom-page.stx', isDynamic: false, params: [] },
  { pattern: '/errors/tester', filePath: 'storage/framework/defaults/resources/views/errors/tester.stx', isDynamic: false, params: [] },
  { pattern: '/', filePath: 'resources/views/index.stx', isDynamic: false, params: [] },
  { pattern: '/about', filePath: 'resources/views/about.stx', isDynamic: false, params: [] },
  { pattern: '/blog', filePath: 'resources/views/blog.stx', isDynamic: false, params: [] },
  { pattern: '/cart', filePath: 'storage/framework/defaults/resources/views/cart.stx', isDynamic: false, params: [] },
  { pattern: '/coming-soon', filePath: 'storage/framework/defaults/resources/views/coming-soon.stx', isDynamic: false, params: [] },
  { pattern: '/dashboard', filePath: 'storage/framework/defaults/resources/views/dashboard/index.stx', isDynamic: false, params: [] },
  { pattern: '/projects', filePath: 'resources/views/projects.stx', isDynamic: false, params: [] },
  { pattern: '/uses', filePath: 'resources/views/uses.stx', isDynamic: false, params: [] },
  { pattern: '/blog/:slug', filePath: 'resources/views/blog/[slug].stx', isDynamic: true, params: ["slug"] },
  { pattern: '/orders/:id', filePath: 'storage/framework/defaults/resources/views/orders/[id].stx', isDynamic: true, params: ["id"] },
] as const

export type RouteName = typeof routes[number]['pattern']
