// Auto-generated by STX - do not edit
declare module '@stacksjs/stx' {
  interface KnownRoutes {
    '/': {  }
    '/about': {  }
    '/apps': {  }
    '/blog': {  }
    '/goals': {  }
    '/home': {  }
    '/projects': {  }
    '/stacks': {  }
    '/uses': {  }
    '/wip': {  }
    '/blog/:slug': { slug: string }
  }
}

export {}
