// Auto-generated by STX - do not edit
declare module '@stacksjs/stx' {
  interface KnownRoutes {
    '/checkout/contact': {  }
    '/checkout/payment': {  }
    '/checkout/shipping': {  }
    '/dashboard/custom-page': {  }
    '/errors/tester': {  }
    '/': {  }
    '/about': {  }
    '/apps': {  }
    '/blog': {  }
    '/cart': {  }
    '/coming-soon': {  }
    '/dashboard': {  }
    '/goals': {  }
    '/projects': {  }
    '/uses': {  }
    '/blog/:slug': { slug: string }
    '/orders/:id': { id: string }
  }
}

export {}
