/**
 * Regenerates public/sitemap.xml.
 *
 * Routes are derived rather than listed: every `resources/views/*.stx` is a
 * page (stx maps the file tree to routes), and every `content/blog/*.md` is a
 * post. That way a new page or post shows up in the sitemap by existing,
 * which is the only way a hand-kept list stays honest.
 *
 * `lastmod` comes from the post's frontmatter date where there is one, and the
 * file's mtime otherwise. Drafts in `content/drafts` are deliberately skipped —
 * they are not routed, so listing them would advertise 404s.
 *
 * Run: bun scripts/build-sitemap.ts
 * Also runs on every deploy (see `preStart` in config/cloud.ts), so the shipped
 * file matches the pages that actually shipped.
 */
import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import process from 'node:process'

const SITE = 'https://chrisbreuer.me'
const root = join(import.meta.dir, '..')

interface Entry { loc: string, lastmod: string, priority: string }

const iso = (d: Date) => d.toISOString().slice(0, 10)

const entries: Entry[] = []

// Static pages, from the view files themselves.
const viewsDir = join(root, 'resources/views')
for (const file of readdirSync(viewsDir)) {
  if (!file.endsWith('.stx')) continue
  const name = file.replace(/\.stx$/, '')
  // `[slug].stx` and friends are templates, not pages.
  if (name.includes('[')) continue
  const path = name === 'index' ? '/' : `/${name}`
  entries.push({
    loc: `${SITE}${path}`,
    lastmod: iso(statSync(join(viewsDir, file)).mtime),
    priority: path === '/' ? '1.0' : '0.8',
  })
}

// Posts.
const blogDir = join(root, 'content/blog')
if (existsSync(blogDir)) {
  for (const file of readdirSync(blogDir)) {
    if (!file.endsWith('.md')) continue
    const full = join(blogDir, file)
    const raw = readFileSync(full, 'utf-8')
    const fm = raw.match(/^---\n([\s\S]*?)\n---/)
    let date = ''
    if (fm) {
      const line = fm[1].split('\n').find(l => l.trim().startsWith('date:'))
      if (line) date = line.slice(line.indexOf(':') + 1).trim().replace(/^['"]|['"]$/g, '').slice(0, 10)
    }
    entries.push({
      loc: `${SITE}/blog/${file.replace(/\.md$/, '')}`,
      lastmod: /^\d{4}-\d{2}-\d{2}$/.test(date) ? date : iso(statSync(full).mtime),
      priority: '0.6',
    })
  }
}

entries.sort((a, b) => a.loc.localeCompare(b.loc))

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/build-sitemap.ts. Do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${entries.map(e => `  <url>
    <loc>${e.loc}</loc>
    <lastmod>${e.lastmod}</lastmod>
    <priority>${e.priority}</priority>
  </url>`).join('\n')}
</urlset>
`

const out = join(root, 'public/sitemap.xml')
writeFileSync(out, xml)
process.stdout.write(`wrote public/sitemap.xml, ${entries.length} urls\n`)
for (const e of entries) process.stdout.write(`  ${e.loc}\n`)
